#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=$PATH:~/bin

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


### ALIASES ###

# add ssh key to something, don't need to re-auth ssh key each time
alias sshkey='ssh-add -K ~/.ssh/id_rsa'

# mac ssh agent woes
alias killssh='killall ssh-agent;killall ssh;ssh-add ~/.ssh/id_rsa'

# study ckad
alias studyckad="open -a Firefox 'https://www.udemy.com/course/certified-kubernetes-application-developer/learn' && code ~/github/private_notes/ckad"

# kube
alias k='kubectl'

# kubectl auto complete
[[ /usr/local/bin/kubectl ]] && source <(kubectl completion zsh)

### Linode-specific ###

# hss for scping files
alias pcs='scp -S hss'

# linagios test linode
alias sshlinagios='ssh root@96.126.108.120'

# my siege linode
alias sshsiege='ssh root@23.239.30.73'

# my big linode
alias sshbeefy='ssh root@23.92.26.83'

# my vanilla debian test linode
alias sshdebian='ssh root@45.79.143.149'

alias startvpn='osascript -e "tell application \"/Applications/Tunnelblick.app\"" -e "connect \"SSL VPN\"" -e "end tell"'

# ansible linode
alias sshansible="ssh -A root@50.116.55.145"

### ENVIRONMENT VARS ###


export KUBE_EDITOR=/usr/bin/vim
export VISUAL=/usr/local/bin/vim

export PATH="/usr/local/opt/ruby/bin:$PATH"
#export PATH="/Users/wbollock/.gem/ruby/3.0.0/bin:$PATH"
export PATH="/usr/local/lib/ruby/gems/3.0.0/bin/:$PATH"

export PATH="/Users/wbollock/.cargo/bin/:$PATH"

# some Montery stuff
export APPLE_SSH_ADD_BEHAVIOR="macos"

# fix term colors for tmux
# https://unix.stackexchange.com/questions/1045/getting-256-colors-to-work-in-tmux
export TERM=xterm-256color


## Launch caffeine in the background
#if ! command -v caffeinate &> /dev/null; then
#     screen -dmS caffeinate caffeinate -u -d -i -m -s
#fi

### brew curl vars ###
# needed for compilers to use curl #
export LDFLAGS="-L/usr/local/opt/curl/lib"
export CPPFLAGS="-I/usr/local/opt/curl/include"
export PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"


### MISC CONFIGS ###

# https://unix.stackexchange.com/questions/212127/zsh-disable-file-exists-warning-with-redirection
setopt clobber

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
