---
# tasks file for common

- name: Do MacOS needfuls
  import_tasks: macos_setup.yml
  when: ansible_facts['os_family']|lower == 'darwin' 

- name: Install packages
  import_tasks: pkg.yml

- name: Configure packages
  import_tasks: configuration.yml
