---
# install packages

- name: Install sane packages
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - git
    - vim
    - tmux
    - tldr
    - jq
    - curl
    - fzf
    - perl
    - nmap
    - tree
    - wget
    - s3cmd
    - pssh
    - ansible
    - ansible-lint
    - wireshark
    - htop
    - ripgrep
