---
# install packages

- name: Install sane packages
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - git
    - vim
    - tmux
    - tldr
    - jq
    - curl
    - fzf
    - perl
    - nmap
    - tree
    - wget
    - s3cmd
    - pssh
    - wireshark
    - htop
    - ripgrep
    - nodejs
    - shellcheck
    # - npm

- name: Install ansible
  ansible.builtin.pip:
    name: ansible
    extra_args: --user

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items:
    - linode-cli
    - salt-lint
    - pytest
    - testinfra
    - 2to3
    - black
    - ansible
    - ansible-lint
    - pynvim
